metal_llm_report_usage() {
    metal_llm_error 'usage: metal-llm report [--check]'
    return 2
}

metal_llm_validate_result() {
    local result_file=$1

    jq -e '
      .schema_version == 1 and
      (.experiment_id | type == "string" and test("^[a-z0-9]+([.-][a-z0-9]+)*$")) and
      (.date | type == "string" and test("^[0-9]{4}-[0-9]{2}-[0-9]{2}$")) and
      (.model_id | type == "string" and test("^[a-z0-9]+([.-][a-z0-9]+)*$")) and
      ((has("summary") | not) or
        (.summary | type == "object") and
        (.summary.output | type == "string" and test("^[a-z0-9.-]+\\.md$")) and
        (.summary.title | type == "string" and length > 0)) and
      (.runs | type == "array" and length > 0) and
      all(.runs[];
        ([.id, .experiment, .measurement_kind, .timestamp, .repository_revision,
          .hardware_id, .runtime_id, .runtime_revision, .profile, .notes] |
          all(type == "string" and length > 0)) and
        (.measurement_kind == "single_run" or .measurement_kind == "three_run_mean") and
        (.timestamp | test("^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$")) and
        (.repository_revision | test("^[0-9a-f]{40}$")) and
        (.runtime_revision | test("^[0-9a-f]{40}$")) and
        (.effective_prompt_tokens | type == "number" and . >= 0 and floor == .) and
        (.generated_tokens | type == "number" and . >= 0 and floor == .) and
        (.prompt_tokens_per_second | type == "number" and . >= 0) and
        (.generation_tokens_per_second | type == "number" and . >= 0) and
        (.generation_settings | type == "object") and
        (.generation_settings.temperature | type == "number") and
        (.generation_settings.seed | type == "number" and floor == .) and
        (.generation_settings.max_tokens | type == "number" and . >= 0 and floor == .) and
        ((has("output_sha256") | not) or
          (.output_sha256 | type == "string" and test("^[0-9a-f]{64}$")))
      )
    ' "$result_file" >/dev/null 2>&1 || {
        metal_llm_die "invalid result document: ${result_file#$METAL_LLM_ROOT/}"
        return 1
    }

    local unsafe_path secret_key
    unsafe_path=$(jq -r '[.. | strings | select(startswith("/" + "Users" + "/"))][0] // empty' "$result_file") || return 1
    [[ -z "$unsafe_path" ]] || {
        metal_llm_die "unsafe private path in ${result_file#$METAL_LLM_ROOT/}"
        return 1
    }
    secret_key=$(jq -r '[.. | objects | keys[] |
      select(test("(^|[_-])(api[_-]?key|access[_-]?token|token|password|secret)($|[_-])"; "i"))][0] // empty' \
      "$result_file") || return 1
    [[ -z "$secret_key" ]] || {
        metal_llm_die "secret-like key in ${result_file#$METAL_LLM_ROOT/}: $secret_key"
        return 1
    }

    local hardware_id runtime_id
    for hardware_id in "${(@f)$(jq -r '.runs[].hardware_id' "$result_file" | sort -u)}"; do
        [[ -f "$METAL_LLM_ROOT/manifests/hardware/$hardware_id.json" ]] || {
            metal_llm_die "unknown hardware id: $hardware_id"
            return 1
        }
    done
    for runtime_id in "${(@f)$(jq -r '.runs[].runtime_id' "$result_file" | sort -u)}"; do
        [[ -f "$METAL_LLM_ROOT/manifests/runtimes/$runtime_id.json" ]] || {
            metal_llm_die "unknown runtime id: $runtime_id"
            return 1
        }
    done
}

metal_llm_generate_summary() {
    local result_file=$1
    local raw_name=${result_file:t}
    jq -r --arg raw_name "$raw_name" '
      def comma:
        tostring | if length <= 3 then . else
          (length % 3) as $first |
          if $first == 0 then 3 else $first end as $head |
          .[0:$head] + ([.[ $head: ] | scan(".{3}")] | if length == 0 then "" else "," + join(",") end)
        end;
      def shown($field; $display):
        if has($display) then .[$display] else (.[$field] | tostring) end;
      def table($rows): $rows | join("\n");
      . as $root |
      [
        "# " + .summary.title,
        "",
        "> Generated by `metal-llm report` from [`../raw/" + $raw_name + "`](../raw/" + $raw_name + "). Do not edit this file by hand.",
        "",
        "These are machine-specific measurements captured on September 3, 2026. Single runs, three-run means, sample standard deviations, interpolation, interpretation, and future work are labeled separately.",
        "",
        "## Runtime comparison (three-run means)",
        "",
        "| Runtime | Cache depth | Prompt tok/s | Generation tok/s |",
        "| --- | ---: | ---: | ---: |"
      ] +
      ([.runs[] | select(.experiment == "runtime-comparison") |
        "| " + .notes + " | " + (.cache_depth | comma) + " | " + shown("prompt_tokens_per_second"; "prompt_tokens_per_second_display") + " | " + shown("generation_tokens_per_second"; "generation_tokens_per_second_display") + " |"] ) +
      [
        "",
        .interpretation.runtime_comparison_limit,
        "",
        "## Matched short-context MTP A/B (single runs)",
        "",
        "| Mode | Generation tok/s | Draft acceptance | Output |",
        "| --- | ---: | ---: | --- |"
      ] +
      ([.runs[] | select(.experiment == "matched-mtp-ab") |
        "| " + (if .mtp then "MTP on, max 2 draft tokens" else "MTP off" end) + " | " + shown("generation_tokens_per_second"; "generation_tokens_per_second_display") + " | " + (.draft_acceptance // "n/a") + " | " + (if .output_equivalence == "byte_identical" then "Byte-identical" else .output_equivalence end) + " |"] ) +
      [
        "",
        "The recorded matched run improved from " + ([.runs[] | select(.id == "matched-no-mtp")][0] | shown("generation_tokens_per_second"; "generation_tokens_per_second_display")) + " to " + ([.runs[] | select(.id == "matched-mtp")][0] | shown("generation_tokens_per_second"; "generation_tokens_per_second_display")) + " tok/s (+50.5%) and produced byte-identical output. This one comparison does not establish universal output equivalence.",
        "",
        "## Long-context retrieval and validation",
        "",
        "| Check | Result |",
        "| --- | --- |"
      ] +
      ([.validations[] | "| " + .check + " | " + .result + " |"] ) +
      [
        "",
        .interpretation.retrieval_budget_note,
        "",
        "## Attached-image crossover (single runs)",
        "",
        "| Effective prompt tokens | No MTP | MTP | Draft acceptance |",
        "| ---: | ---: | ---: | ---: |"
      ] +
      ([.runs | group_by(.effective_prompt_tokens)[] |
        select(.[0].experiment == "attached-image-crossover") |
        (map(select(.mtp == false))[0]) as $off |
        (map(select(.mtp == true))[0]) as $on |
        "| " + (.[0].effective_prompt_tokens | comma) + " | " + ($off | shown("generation_tokens_per_second"; "generation_tokens_per_second_display")) + " | " + ($on | shown("generation_tokens_per_second"; "generation_tokens_per_second_display")) + " | " + $on.draft_acceptance + " |"] ) +
      [
        "",
        .interpretation.crossover_note,
        "",
        "## Vision-loaded, text-only boundary (three-run means and sample SD)",
        "",
        "| Prompt tokens | No MTP mean | No MTP SD | MTP mean | MTP SD | MTP change |",
        "| ---: | ---: | ---: | ---: | ---: | ---: |"
      ] +
      ([.runs | group_by(.effective_prompt_tokens)[] |
        select(.[0].experiment == "text-boundary-mean") |
        (map(select(.mtp == false))[0]) as $off |
        (map(select(.mtp == true))[0]) as $on |
        "| " + (.[0].effective_prompt_tokens | comma) + " | " + ($off | shown("generation_tokens_per_second"; "generation_tokens_per_second_display")) + " | " + ($off.generation_tokens_per_second_sd_display // ($off.generation_tokens_per_second_sd | tostring)) + " | " + ($on | shown("generation_tokens_per_second"; "generation_tokens_per_second_display")) + " | " + ($on.generation_tokens_per_second_sd_display // ($on.generation_tokens_per_second_sd | tostring)) + " | " + $on.change_display + " |"] ) +
      [
        "",
        "## Vision-loaded, text-only calibration (single runs)",
        "",
        "| Prompt tokens | No MTP | MTP |",
        "| ---: | ---: | ---: |"
      ] +
      ([.runs | group_by(.effective_prompt_tokens)[] |
        select(.[0].experiment == "text-boundary-single") |
        (map(select(.mtp == false))[0]) as $off |
        (map(select(.mtp == true))[0]) as $on |
        "| " + (.[0].effective_prompt_tokens | comma) + " | " + ($off | shown("generation_tokens_per_second"; "generation_tokens_per_second_display")) + " | " + ($on | shown("generation_tokens_per_second"; "generation_tokens_per_second_display")) + " |"] ) +
      [
        "",
        .interpretation.corrected_long_context_note,
        "",
        "## Interpretation and limits",
        "",
        "The repeated general-purpose gray zone is approximately 29–30K effective tokens. " + .interpretation.routing_guidance,
        "",
        .interpretation.output_behavior,
        "",
        .interpretation.limitation
      ] | table(.)
    ' "$result_file"
}

metal_llm_generate_generic_summary() {
    local result_file=$1
    jq -r '
      def comma:
        tostring | if length <= 3 then . else
          (length % 3) as $first |
          if $first == 0 then 3 else $first end as $head |
          .[0:$head] + ([.[ $head: ] | scan(".{3}")] | if length == 0 then "" else "," + join(",") end)
        end;
      def shown($field; $display):
        if has($display) then .[$display] else (.[$field] | tostring) end;
      [
        "# Benchmark result: " + .experiment_id,
        "",
        "| Run | Experiment | Prompt tokens | Generated tokens | Prompt tok/s | Generation tok/s |",
        "| --- | --- | ---: | ---: | ---: | ---: |"
      ] +
      [.runs[] |
        "| " + .id + " | " + .experiment + " | " + (.effective_prompt_tokens | comma) +
        " | " + (.generated_tokens | comma) + " | " +
        shown("prompt_tokens_per_second"; "prompt_tokens_per_second_display") + " | " +
        shown("generation_tokens_per_second"; "generation_tokens_per_second_display") + " |"
      ] | join("\n")
    ' "$result_file"
}

metal_llm_report() {
    local check=0
    if (( $# > 1 )); then
        metal_llm_report_usage
        return $?
    fi
    if (( $# == 1 )); then
        [[ "$1" == --check ]] || { metal_llm_report_usage; return $?; }
        check=1
    fi
    command -v jq >/dev/null 2>&1 || { metal_llm_die 'jq is required'; return 1; }

    local result_file output_name summary_path generated temporary_summary
    typeset -a result_files
    result_files=("$METAL_LLM_ROOT"/results/raw/*.json(N))
    (( ${#result_files} > 0 )) || { metal_llm_die 'no raw result documents found'; return 1; }

    for result_file in "${result_files[@]}"; do
        metal_llm_validate_result "$result_file" || return 1
        output_name=$(jq -r '.summary.output // empty' "$result_file") || return 1
        if [[ -z "$output_name" ]]; then
            if (( check == 0 )); then
                metal_llm_generate_generic_summary "$result_file" || return 1
            fi
            continue
        fi
        summary_path="$METAL_LLM_ROOT/results/summaries/$output_name"
        generated=$(metal_llm_generate_summary "$result_file") || return 1
        if (( check == 1 )); then
            [[ -f "$summary_path" ]] || {
                metal_llm_die "summary is missing: ${summary_path#$METAL_LLM_ROOT/}"
                return 1
            }
            cmp -s <(print -r -- "$generated") "$summary_path" || {
                metal_llm_die "summary differs from generated output: ${summary_path#$METAL_LLM_ROOT/}"
                return 1
            }
        else
            mkdir -p "$summary_path:h"
            temporary_summary=$(mktemp "$summary_path.part.XXXXXX") || return 1
            if ! print -r -- "$generated" > "$temporary_summary"; then
                rm -f -- "$temporary_summary"
                return 1
            fi
            mv -f -- "$temporary_summary" "$summary_path" || return 1
            print -r -- "$generated"
        fi
    done
}
